### ISSUE TITLE
How to start jetty server

### ISSUE THREAD

**Issue by pingsutw** [simenflatby/jersey-swagger-ui-example#2]
Thanks for the great explanation about swagger with jetty, but I don't know how to start the server.
it will be great if you provide related command in the readme.

**Comment by simenflatby** [comment]
Hi @pingsutw. This repo is just the full code example for this article: https://medium.com/shark-bytes/co-hosting-swagger-ui-with-your-jersey-rest-api-using-maven-dependencies-44d88ae85bf8

This article does not focus on how to start a server because it is not an example for a specific server type. You can for example run it on Tomcat via IntelliJ as shown in chapter 4 of this example: https://medium.com/@backslash112/create-maven-project-with-servlet-in-intellij-idea-2018-be0d673bd9af

Good luck :)

**Comment by pingsutw** [comment]
@simenflatby Thanks for the help
